export const MODULES_RESPONSE = 'MODULES_RESPONSE';
export const MODULES_UPDATED_RESPONSE = 'MODULES_UPDATED_RESPONSE';
export const MODULES_DESTROYED_RESPONSE = 'MODULES_DESTROYED_RESPONSE';
export const MODULES_ERROR_RESPONSE = 'MODULES_ERROR_RESPONSE';
export const PLACEMENTS_RESPONSE = 'PLACEMENTS_RESPONSE';
export const PLACEMENTS_UPDATED_RESPONSE = 'PLACEMENTS_UPDATED_RESPONSE';
export const PLACEMENTS_DESTROYED_RESPONSE = 'PLACEMENTS_DESTROYED_RESPONSE';
export const PLACEMENTS_ERROR_RESPONSE = 'PLACEMENTS_ERROR_RESPONSE';
